name: Java (Gradle) Release

on:
  workflow_call:
    secrets:
      token:
        required: true
      passwd:
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare local repo
        run: |
          # Get remote tags
          git fetch --tags
          # Get permission to run gradle script
          chmod +x gradlew

      - name: Set up packages
        run: |
          sudo apt update
          sudo apt install msmtp mutt jq
          cat > ~/.msmtprc <<EOF
          # Gmail configuration
          account default
          host smtp.gmail.com
          port 587
          auth on
          tls on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          user ansorensen1118@gmail.com
          password ${{ secrets.PASSWD }}
          from ansorensen1118@gmail.com
          logfile ~/.msmtp.log
          EOF
          
          chmod 600 ~/.msmtprc
          
          cat > ~/.muttrc <<EOF
          set sendmail="/usr/bin/msmtp"
          set use_from=yes
          set realname="Anston Sorensen"
          set from="ansorensen1118@gmail.com"
          EOF

      - name: Get Java version
        id: retrieve_java
        run: |
          target=$(grep -oP 'languageVersion\.set\(JavaLanguageVersion\.of\(\K[0-9]+' build.gradle.kts)
          echo "target=$target" >> $GITHUB_ENV
          echo "This project requires JDK version $target"

      - name: Download JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '${{ env.target }}'
          
      - name: Determine current version
        id: determine_version
        run: |
          version_num=$(grep -oP 'version\s*=\s*"\K[^"]+' build.gradle.kts)
          if [[ $version_num == *SNAPSHOT* ]]; then
            echo "snapshot=true" >> $GITHUB_ENV
            echo "Snapshot version detected. Nothing to do here"
          else
            echo "version_num=$version_num" >> $GITHUB_ENV
            echo "The current version is $version_num"
          fi
          
      - name: Get last version
        id: last_version
        if: ${{ env.snapshot != 'true' }}
        run: |
         last_commit=$(git rev-list --tags --max-count=1)
         if [[ $last_commit == "" ]]; then
           echo "There are no previous tags. There could have been an early snapshot version"
           last_commit=$(git rev-list --max-parents=0 HEAD)
           changed="true"
           echo "changed=$changed" >> $GITHUB_ENV
         else
           echo "The hash of the last tag commit is $last_commit"
           echo "last_commit=$last_commit" >> $GITHUB_ENV
           last_version=$(git describe --tags $last_commit)
           last_version_num=${last_version//"v"/}
           echo "last_version_num=$last_version_num" >> $GITHUB_ENV
           echo "The last version was $last_version_num"
         fi

      - name: Check if version has changed
        id: version_changed
        if: ${{ env.snapshot != 'true' && env.changed != 'true' }}
        run: |
         changed="${{ env.version_num != env.last_version_num }}"
         echo "changed=$changed" >> $GITHUB_ENV
         if [[ $changed == true ]]; then
           echo "The plugin has updated! The version has changed from ${{ env.last_version_num }} to ${{ env.version_num }}"
         else
           echo "The plugin version hasn't changed"
         fi

      - name: Build JAR file
        id: build_jar
        if: ${{ env.changed == 'true' }}
        run: |
          ./gradlew build
          if [[ ${{ github.ref }} == refs/heads/main || ${{ github.ref }} == refs/heads/master ]]; then
            echo "main_branch=true" >> $GITHUB_ENV
          else
            echo "main_branch=false" >> $GITHUB_ENV
          fi

      - name: Generate release notes
        id: release_notes
        if: ${{ env.main_branch == 'true' }}
        run: |
         # Get the hash of the last commit
         last_commit=${{ env.last_commit }}
         echo "The hash of the last version's commit is $last_commit"

         # Get commit messages since then
         commit_messages="$(git log --pretty=format:"%s" $last_commit..HEAD)"
          
         if [[ $commit_message != "" ]]; then
           printf "Here are the new commit messages! \n$commit_messages"
          
           # Generate end of file delimiter
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          
           #Initialize release_notes
           echo "release_notes<<$EOF" >> $GITHUB_ENV
          
           # Add each line
           echo "$commit_messages" | while IFS= read -r line
           do
              echo "* $line" >> $GITHUB_ENV
           done
          
           # Finish
           echo "$EOF" >> $GITHUB_ENV
         else
           echo "No new commit messages. Assuming it was only a version change"
           release_notes="* Updated version to ${{ env.version_num }}"
           echo "release_notes=$release_notes" >> $GITHUB_ENV
         fi

      - name: Create release
        id: create_release
        if: ${{ env.main_branch == 'true' }}
        run: |
          echo "Pushing tag for release..."
          git tag v${{ env.version_num }} ${{ github.sha }}
          git push origin tag v${{ env.version_num }}
          echo "Creating release with the following info..."
          echo "Tag: v${{ env.version_num }}"
          echo "Name: ${{ env.version_num }}"
          echo "Body: "
          echo "${{ env.release_notes }}"
          id=$( curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{"tag_name":"v${{ env.version_num }}","name":"${{ env.version_num }}","body":"${{ env.release_notes }}","draft":false,"prerelease":false,"generate_release_notes":true}' | jq '.id' )
          echo "The ID is $id"
          echo "id=$id" >> $GITHUB_ENV

      - name: Upload assets
        if: ${{ env.main_branch == 'true' }}
        run: |
          file_name=$(find build/libs/ -type f -name "*.jar" ! -name "*dev.jar" ! -name "*dev-all.jar")
          file_name_f=${file_name// /-}
          if [[ $file_name != $file_name_f ]]; then
            mv "$file_name" "$file_name_f"
          fi
          echo "The JAR file relative name is $file_name_f"
          base_name=$(basename "$file_name_f")
          echo "The JAR file base name is $base_name"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: multipart/form-data" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.id }}/assets?name=$base_name" \
            --data-binary "@$file_name_f"

      - name: Notify author
        if: ${{ env.main_branch == 'true' }}
        run: |
         cat > email_body.html <<EOF
         <html>
         <body>
           <a href="https://github.com/${{ github.repository }}/releases/tag/v${{ env.version_num }}">Release v${{ env.version_num }}</a> has been automatically published!<br><br>
           Commits:<br>
           ${{ env.release_notes }}<br><br>
           Best regards,<br>
           ${{ runner.name }} Runner
         </body>
         </html>
         EOF
         mutt -e 'set content_type=text/html' -s "[${{ github.repository }}] Release v${{ env.version_num }} Published" ansorensen1118@gmail.com < email_body.html
